### ISSUE TITLE
An API error 

### ISSUE THREAD

**Issue by krahimov** [plaid/income-sample#11]
Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON. The error occurred after the browser list update happened   (npx browserslist@latest --update-db)

**Comment by phoenixy1** [comment]
@krahimov I wasn't able to reproduce this issue. If it's still a problem for you, can you provide a more detailed repro case so we can look into it further?

**Comment by atim124** [comment]
7b4db1ff2f9c8a20ae195d2f6835b5f610f5e04b

**Comment by atim124** [comment]
7b4db1ff2f9c8a20ae195d2f6835b5f610f5e04b

**Comment by atim124** [comment]
7b4db1ff2f9c8a20ae195d2f6835b5f610f5e04b
