### ISSUE TITLE
Module not found: Error: Can't resolve 'framer-motion' in

### ISSUE THREAD

**Issue by mijaelsaban** [plaid/income-sample#13]
ERROR in ./node_modules/@chakra-ui/progress/dist/chakra-ui-progress.esm.js 30:11-20
export 'keyframes' (imported as 'keyframes') was not found in '@chakra-ui/system' (possible exports: CSSVars, ColorModeContext, ColorModeProvider, ColorModeScript, DarkMode, GlobalStyle, LightMode, StylesProvider, ThemeProvider, addPrefix, background, border, calc, chakra, color, cookieStorageManager, css, cssVar, effect, filter, flattenTokens, flexbox, forwardRef, getCss, grid, interactivity, isStyleProp, layout, layoutPropNames, list, localStorageManager, omitThemingProps, others, position, propNames, pseudoPropNames, pseudoSelectors, ring, scroll, setScript, shouldForwardProp, space, storageKey, styled, systemProps, textDecoration, toCSSObject, toCSSVar, toVarDefinition, toVarReference, tokenToCSSVar, transform, transition, typography, useChakra, useColorMode, useColorModeValue, useMultiStyleConfig, useProps, useStyleConfig, useStyles, useTheme, useToken)

I am getting this error
npm -v : 8.19.3
node v: 18.20-4

**Comment by phoenixy1** [comment]
Try deleting your `npm_modules` folder and installing with `npm ci`

**Comment by mijaelsaban** [comment]
I could solve it by doing 

`npm i --save  babel-preset-env babel-preset-react`

no idea why and how but now works,

Thanks
