### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by MaxJadav** [plaid/income-sample#6]
When try to start server npm start  throw error:

![Screenshot 2022-10-05 at 6 21 19 PM](https://user-images.githubusercontent.com/31030098/194065601-07013e4c-db83-41b9-9161-872d04226b62.png)

**Comment by phoenixy1** [comment]
@MaxJadav I was unable to reproduce this issue when trying just now, and we haven't had any other reports of it, so it may be something specific to your configuration. Some suggestions for troubleshooting: 

1) Blow away your local repo and re-clone the project from scratch, then make sure you set it up following all the instructions in the readme
2) Check your Plaid dashboard activity log (https://dashboard.plaid.com/activity/logs) to see if any errors are present there
3) Ensure you are using the latest version of node
