### ISSUE TITLE
No Payroll Providers Available

### ISSUE THREAD

**Issue by vzirshehryar** [plaid/income-sample#9]
I have integrated income payroll and income bank in my app and I can connect bank in there but when I open the link for payroll, no options are available there for payroll provider, or any other thing. I can see errors in console. Attaching the error screen
<img width="1440" alt="Screenshot 2024-05-22 at 2 26 54 PM" src="https://github.com/plaid/income-sample/assets/95472169/7b57fe3f-5d11-4531-9b3e-f752d534bc03">

**Comment by phoenixy1** [comment]
closing this out as stale, please feel free to reopen if it is still an issue
